local options = {
  incsearch = true,
  backup = false,
  writebackup = false,
  swapfile = false,
  undofile = true,
  updatetime = 100,
  termguicolors = true,
  clipboard = "unnamedplus",
  cmdheight = 1,
  fileencoding = "utf-8",
  hlsearch = true,
  ignorecase = true,
  mouse = "a",
  pumheight = 10,
  showtabline = 0,
  smartcase = true,
  smartindent = true,
  splitbelow = true,
  splitright = true,
  tabstop = 2,
  expandtab = true,
  cursorline = true,
  number = true,
  relativenumber = true,
  numberwidth = 4,
  signcolumn = "yes",
  wrap = false,
  scrolloff = 8,
  sidescrolloff = 8,
  laststatus = 3,
  showcmd = false,
  ruler = false,
  title = true,
}

for k, v in pairs(options) do
    vim.opt[k] = v
end
